// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sumitrack.Api.Infrastructure.Data;

#nullable disable

namespace Sumitrack.Api.Infrastructure.Data.Migrations.Public;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Sumitrack.Api.Models.Entities.Tenant", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("NOW()");

            b.Property<string>("SchemaName")
                .IsRequired()
                .HasMaxLength(63)
                .HasColumnType("character varying(63)")
                .HasColumnName("schema_name");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("slug");

            b.HasKey("Id")
                .HasName("pk_tenants");

            b.HasIndex("SchemaName")
                .IsUnique()
                .HasDatabaseName("ix_tenants_schema_name");

            b.HasIndex("Slug")
                .IsUnique()
                .HasDatabaseName("ix_tenants_slug");

            b.ToTable("tenants", "public");
        });
#pragma warning restore 612, 618
    }
}
